services:
  english-word:
    # 替换 build: . 为 image: 指定已有镜像
    image: english_word-english-word:latest
    container_name: english-word-app
    ports:
      - "3010:3010"
    volumes:
      - english-word-db:/app/data
    environment:
      - PORT=3010
      - DB_PATH=/app/data/words.db
    restart: always

volumes:
  english-word-db: