services:
  english-word:
    build: .
    image: english_word-english-word:latest
    container_name: english-word-app
    ports:
      - '${PORT:?PORT is required}:${PORT:?PORT is required}'
    volumes:
      - english-word-db:/app/data
    environment:
      PORT: ${PORT:?PORT is required}
      DB_PATH: ${DB_PATH:?DB_PATH is required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?ADMIN_PASSWORD is required}
    restart: always

volumes:
  english-word-db:
    driver: local
